# Site settings
title: monome
email: help@monome.org
description: > # this means to ignore newlines until "baseurl:"
  adaptable minimalist interfaces.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://monome.org"
# twitter_username: monomes
# github_username:  monome

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: lua
    css_class: 'highlight'

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
